### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Righted1** [jluims/RobloxGen#2]
`Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'dotenv' imported from C:\Users\stefa\OneDrive\Bureau\RobloxGen-main\src\index.js
    at packageResolve (internal/modules/esm/resolve.js:650:9)
    at moduleResolve (internal/modules/esm/resolve.js:691:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:805:11)
    at Loader.resolve (internal/modules/esm/loader.js:88:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:241:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:72:40)
    at link (internal/modules/esm/module_job.js:71:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! robloxgen@1.0.0 start: `node src/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the robloxgen@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
`

**Comment by jluims** [comment]
Make sure to run npm install first

**Comment by jluims** [comment]
My bad, I screwed up the readme file
